version: "1"

services:
  db:
    image: postgres
    container_name: PostgreSQL
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - default
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: Nginx
    ports:
      - 80:80
    networks:
      - default
  php:
    build:
      context: .
      args:
        USER: ${USER}
    container_name: Symfony6.3
    volumes:
      - symfonydata:/var/www/html
    networks:
      - default
volumes:
  pgdata:
  symfonydata: